var lesson=[];
function l(lec, ovn, txt){
    if(!(lec in lesson)) lesson[lec] = [];
    lesson[lec][ovn] = txt;
}

l(1,1,"fff jjj fff jjj fjfj fjfj jfjf jfjf ff jf fj ffj fj fjffj jf");
l(1,2,"aa ss dd ff asdf asdf adsf adsf fdsa fdsa fdsa fdsa dfsas sf");
l(1,3,"jj kk ll öö jklö jklö jklö jklö ölkj ölkj öljk öljk ölklj jk");
l(1,4,"asdf jklö ölkj fdsa asdf jklö ölkj fdsa fjdk slaö fjdk slaöj");
l(1,5,"sl kd fj aö as öl kd jf dk sö kd kö sd af fl ls fj kf dk sla");
l(1,6,"ada ada kaka kaka fasa fasa ödla ödla ada kaka fasa ja ja ja");
l(1,7,"fasad fasa dafa lök kall löj flaska klass slask flöd sjö öka");
l(1,8,"flaska kallas klös kalas skal skölja jas sladd dallas sallad");
l(1,9,"slaska slösa sladda slöja dölja kladda flöda föda dala falla");
l(1,10,"slöjd född lödd flaska skala lök klass sallad följd dök köld");
l(1,11,"kladda dök slösa sjö skala fasad skakad dölja adjö adjö adjö");
l(1,12,"slöjd kall flöda öl föll skala jaffa falla följd ösa köl ask");
l(1,13,"dölja döda dala dök död kö ökas ökad föda född sladda slöa öl");
l(1,14,"sallad söka sökad sak ska skall sjö sladda sköld skala skalad");
l(1,15,"kalla kalas kallad kall kladda klaff klas kö klass köld kafka");
l(1,16,"skaka skall klaff falk kalk kalka kalkas kladda sjö sa sak öl");
l(1,17,"kall slö ja ska ask föll dala sladd sak sök söka söla dö löda");
l(1,18,"falla kallas skala skalad öka ödla skölj skölja skada ska sak");
l(1,19,"skal skadad skölja köld fasad föll ja jaffa kaj löda kajak ja");
l(1,20,"kajak kalla kallas kaj klass flaska sjö sjöss kassa kalka sal");
l(2,1,"fff ggg fff ggg fgfgfg ggg gfgfgf ag sg dg fg fjg fjg fg klg");
l(2,2,"jjj hhh jjj hhh jhjhjh hhh hjhjhj gh öh lh kh jhj fh fh hfjh");
l(2,3,"vvv fff vvv fff vfvfvf vvv fvfvfv fgfv fgfv fgv fgv fdv vfsv");
l(2,4,"mmm jjj mmm jjj mjmjmj mmm jmjmjm jhjm jhjm mjhjm mjhjm mkjm");
l(2,5,"äää ööö äää ööö jäjäjä hähähä mämämä äkä älä lölä lölä älölä");
l(2,6,"glögg glad glass glöm glömma flagga ägg dagg glöda gädda göl");
l(2,7,"hall hälla hava hög hal hals hälsa häl haha höll hög höga hö");
l(2,8,"valla vän hava hav döv döva vad kalva halva löv slav vals av");
l(2,9,"mamma mjöl mjäll massa flamma klämdes mala halm hjälm samma");
l(2,10,"öl öka ökad ökas ön ösa flög glöda mö öva övas söva döda dök");
l(2,11,"jag ska kalla jag ska kalka jag ska hälla jag ska lägga jaja");
l(2,12,"mamma ska öva sallads vm mamma ska öva hälla glass ska mamma");
l(2,13,"hala gäss ska skaka av hal mask hal haj ska ägas av alla kaj");
l(2,14,"vagga vagga söva klas mjölka dags massa mjölk ja mm glad mmm");
l(2,15,"läsk flaska mjölk glögg mmm skala ägg sallad döljd mask ajaj");
l(2,16,"lamm mask gök möss kalva gäss gädda haj falk säl daggmask ha");
l(2,17,"hal halka sladda falla aj föll skadad kladda lagas läggas öm");
l(2,18,"mjäll mössa hjälm valsa vals flagga flög hög höll mamma haga");
l(2,19,"glada möss halva dag ska jagas sälja säl hälsa alla alla väl");
l(2,20,"jag ska mala massa mjöl sälja samma dag jag ska sälja mjöl");
l(3,1,"aaa fbfb fbfb fbfb fgfb fgfb fgfvfb fgfvfb fgfbfv vfbfgf bfb");
l(3,2,"ddd dcdc dcdcdc dc dcdc dede de dede de dede dedc dedc dedce");
l(3,3,"ddd eee fff ggg ddee ddff ddgg eeff ffgg fgfg fgfg efef cfcf");
l(3,4,"abcdefg abcdefg abcdefg abcdefg abcdefg abcdefg abcdefg abcd");
l(3,5,"abcj defk gabl cdeö fgav bcd efgh abcn defj gabk cdel agkdcb");
l(3,6,"abba agfa ada anfall alfa bada bas baka be blad bädda blabla");
l(3,7,"dag deg dagg ladda dala dvs egg el eld elda egg jaffa klaffa");
l(3,8,"fall feg flög flöda föll glada ge fega glöd ägg glögg flagga");
l(3,9,"abcdefg gfedcba abcdefg gfecdba abcdefg gfedcba abcdefg gfec");
l(3,10,"kladda glada flagga bada dag fega ge glöd ägg ack fack macka");
l(3,11,"mamma ska föda baka bädda bada damma lägga vagga söva släcka");
l(3,12,"jag ska baka smaka de ska leva klas ska flagga sassa ska öva");
l(3,13,"hej jag ska säga abcd hej abcdefg jag sa abc hej abcdefg hej");
l(3,14,"hej kalle sa klas ack ack sa kalle de ska jaga säl alla alla");
l(3,15,"ska de leva ska de dö ska de väckas ska de sövas glada möss");
l(3,16,"hej adam hej eva hemma hade jag fem smala glada möss fega möss");
l(3,17,"hel helg halva dag elda flamma anfalla hemkallad hälsa skägg");
l(3,18,"gala leka dala smeka glas glass bas kassa falla föll flaska");
l(3,19,"ja jag jagade sa jag glada backa backa hacka fack lacka lack");
l(3,20,"abc defg ab cd efg abba ladda macka flagga hej hej glada mamma");
l(4,1,"jhjh jhjh kiki kiki jhjh kiki jhki jhki jhki ikhj ikhj ikhjh");
l(4,2,"ll ll jmjm jmjm ll jmjm jnjn jnjn k,k, k,k, k,nj k,nj mjmjk,");
l(4,3,"hijk hijk hijk lmn, lmn, lmn, h, i, j, k, l, m, n, k, n, lk,");
l(4,4,"hijklmn, hijklmn, hijklmn, hijklmn, hijklmn, hijklmn, hijklm");
l(4,5,"hkji jm jhij lhj mh jinmh ijmn j mim jlimm jlmkji mjh illmim");
l(4,6,"hi, hej, höj, haha, halm hala il illa, ila, lilla, i, id, ni");
l(4,7,"ja, jag, jämn jama hjälm, lamm namn man massa missa flöda an");
l(4,8,"jag kan, jag kan, jag kan knacka en del, en hel del, kan jag");
l(4,9,"hijklmn, hijklmn, hijklmn, hijklmn, nmlkjih, nmlkjih, hijkl");
l(4,10,"ja, jag kan kalla en bil en dag, ej kan ni kalla en bil idag");
l(4,11,"han ska dansa hela dagen, jag ska väl vila mig, hemma själv");
l(4,12,"nämna namn kan du, men kan du se vad kan hända dig min vän");
l(4,13,"en, fem, elva, kan jag idag ganska väl, även abcdefghijklmns");
l(4,14,"man kanske ska lägga sig innan kl elva, sa niklas mamma en dag");
l(4,15,"en dag gick vi vilse, men vi följde min lilla näsa hem igen");
l(4,16,"isabelle la sig på sängen, funderade länge, david el mikael");
l(4,17,"ska vi hänga med idag, annie ska väl handla en hel del saker");
l(4,18,"en dag fiskade jag med min vän klas, men han ville bada i sjön");
l(4,19,"kvinnan hade en vännina, vänninan hade en vän, en annan vän");
l(4,20,"följ med mig, vi ska ha en skön kväll, sa han, ja med glädje");
l(5,1,"ooo ppp qqq rrr sss ttt uuu ooo ppp qqq rrr sss ttt uuu oooo");
l(5,2,"lolo lolo öpöp öpöp lololo öpöpöp aqaq aqaq löaopq löaopq pq");
l(5,3,"frfr frfr ftft ftft frftfrft juju juju k,k, k,k, juk,juk,juk");
l(5,4,"loöp loöp aqfr aqfr ftju ftju jufr jufr frftfg jujhjn fgtjhu");
l(5,5,"opqrstu, opqrstu, opqrstu, opqrstu, opqrstu, opqrstu, opqrst");
l(5,6,"opus ort offer osund ojoj oljud pappa piper part plasma post");
l(5,7,"rot ropa röka ruta ribba rör sist soppa sport sopa surt stor");
l(5,8,"titta topp tippa total tom test under ur ute utan uselt guru");
l(5,9,"opqrstu, opqrstu, opqrstu, opqrstu, opqrstu, opqrstu, opqrst");
l(5,10,"jag har jobbat bra och kan snart skriva allt, eller vad sägs");
l(5,11,"snart kan jag skriva hela alfabetet, bara fem bokstäver kvar");
l(5,12,"nu gäller det att träna upp hastigheten också, jobba på heja");
l(5,13,"titta, nu kan jag skriva ett t, det var enkelt, ett t till");
l(5,14,"peter piper picked a peck of pickled peppar, p är inte lätt");
l(5,15,"inte q nej, vad ska man ha q till, aqua som i aqua minerale");
l(5,16,"mina herrar, är ni rörda, det rörde oss i rörmokarrörelsen");
l(5,17,"en till på engelska, she sells sea shells on the sea shore");
l(5,18,"här i alvesta finns det maskiner som transporterar dagligen");
l(5,19,"att träffa dig var den bästa saken som har hänt mig i livet");
l(5,20,"januari, februari, mars, april, maj, juni, juli, augusti, mm");
l(6,1,"fvfvfv swsw swsw swsw swsw sxsx sxsx sxsx swsx swsx sxsw swx");
l(6,2,"jyjy jyjy jhjy jhjy jujy juyj azaz azaz azza azza azza zazaz");
l(6,3,"öå öå öå öå öä öä öä ö ä å ö ä å å ä ö öäöå öäöå åå ää öäöåö");
l(6,4,"l.l. l.l. l.l. l.l. åäö. åäö. åäö. sx. sw. fv. jy. az. öl. ö");
l(6,5,"vwxyz vwxyz vwxyz. åöä. åöä. vwxyzåöä. vwxyzåöä. vwxyzåöä.");
l(6,6,"vax vård välkommen veva vrak avstyra avundsjuk avi evig vrål");
l(6,7,"exakt. yxa. vaxa. läxa. lax. sax. flaxa maxim taxi taxa häxa");
l(6,8,"yt yr yla. byn, hy, syr. syra syror syster syskon sympati ny");
l(6,9,"zzz zloty azzuro buzz zara zappa ål så då på gå tå få nå må.");
l(6,10,"vwxyzåäö. vwxyzåäö. vwxyzåäö. vwxyzåäö. vwxyzåäö. vwxyzåäö.");
l(6,11,"nu kan du skriva alla bokstäver, men du måste träna mycket.");
l(6,12,"måndag, tisdag, onsdag, torsdag, fredag, lördag, söndag.");
l(6,13,"röd, gul, blå, vit, grön, lila, rosa, svart, brun, grå.");
l(6,14,"the quick brown fox jumped over the lazy dog. a till z finns.");
l(6,15,"detta är en automatisk telefonsvarare, var god och lämna...");
l(6,16,"exakt när laxen blir klar kan jag inte säga, svarade zara.");
l(6,17,"taxi, taxi, skrek jag, snön vräkte när, klockan var redan sex.");
l(6,18,"ett, två, tre, fyra, fem, sex, sju, åtta, nio, tio, elva, tolv.");
l(6,19,"en häxa hade en yxa, hennes syster gjorde razzia och snodde yxan.");
l(6,20,"ett nytt hus i en by syns tydligt för befolkningen, eller hur.");
l(7,1,"abcdefghij abcdefghij abcdefghij abcdefghij abcdefghij abcde");
l(7,2,"klmnopqrst klmnopqrst klmnopqrst klmnopqrst klmnopqrst klmno");
l(7,3,"uvwxyzåäö. uvwxyzåäö. uvwxyzåäö. uvwxyzåäö. uvwxyzåäö. uvwxy");
l(7,4,"abcdefghijklmno, abcdefghijklmno, pqrstuvwxyzåäö. pqrstuvwxy");
l(7,5,"abcdefghijklmnopqrstuvwxyzåäö. abcdefghijklmnopqrstuvwxyzåäö");
l(7,6,"januari, februari, mars, april, maj, juni, juli, agusti.");
l(7,7,"maj, juni, juli, augusti, september, oktober, november, december.");
l(7,8,"abc, def, ghi, jkl, mno, pqr, stu, vwx, yz, åäö.");
l(7,9,"äpple, blåbär, hallon, jordgubbe, päron, mandarin, apelsin, kiwi.");
l(7,10,"abcdefghijklmnopqrstuvwxyzåäö. abcdefghijklmnopqrstuvwxyzåäö");
l(7,11,"den som är redovisningsskyldig ska utan anmaning lämna deklaration");
l(7,12,"under det senaste decenniet har modern grafisk teknik förändrats.");
l(7,13,"jag minns honom mycket väl fast att det var länge länge sen.");
l(7,14,"jag minns när han gick i sin hage rullade sig och visade magen.");
l(7,15,"abcdefghijklmnopqrstuvwxyzåäö. abcdefghijklmnopqrstuvwxyzåäö.");
l(7,16,"vi tackar för er förfrågning och lämnar följande kostnadsförslag");
l(7,17,"om jag fick välja skulle jag åka till italien, till florens.");
l(7,18,"nu när du kan skriva hela alfabetet kan du skriva vad som helst.");
l(7,19,"the man who makes no mistakes does not usually make anything.");
l(7,20,"en sådan varm och vacker sommardag, ner till sjön måste vi.");
l(8,1,"a1ö0 a1ö0 a1ö0 a1ö0 a1ö0 a1ö0 a1ö0 a1ö0 a1ö0 a1ö0 a1ö0 a1ö00");
l(8,2,"s2l9 s2l9 s2l9 s2l9 s2l9 s2l9 s2l9 s2l9 s2l9 s2l9 s2l9 s2l99");
l(8,3,"+++ --- +++ --- +-+- +-+- +-+- +1 -1 +1 -1 +9 -9 +2 -2 2+9 1+0");
l(8,4,"1290 + 1290 + 1029 + 1029 + 9201 + 9201 + 9201 + 1290 + 1209");
l(8,5,"d3k8 d3k8 d3k8 d3k8 d3k8 d3k8 d3k8 d3k8 d3k8 d3k8 d3k8 d3k88");
l(8,6,"f4j7 f4j7 f4j7 f4j7 f4j7 f4j7 f4j7 f4j7 f4j7 f4j7 f4j7 f4j77");
l(8,7,"1029 + 3847 + 1029 + 3847 + 10293847 + 10293847 + 10293847");
l(8,8,"10293847 - 10293847 + 10293847 - 10293847 + 10293847");
l(8,9,"t5y6 t5y6 t5y6 t5y6 t5y6 t5y6 t5y6 t5y6 t5y6 t5y6 t5y6 t5y66");
l(8,10,"t5y6d3k8 a1ö0s2l9 t5y6d3k8 a1ö0s2l9 t5y6d3k8 a1ö0s2l9 t5y6d3");
l(8,11,"4657 + 4657 - 4657 + 4657 - 4657 + 4657 - 4657 + 4657 - 4657");
l(8,12,"1029 + 4657 - 1029 + 4657 - 3846 + 1029 - 4657 + 3846 - 3846");
l(8,13,"10,29 + 29,38 + 38,47 + 46,50 + 50,10 + 10,29 + 29,38");
l(8,14,"61,29 + 72,38 + 83,47 + 94,56 + 100,0 + 61,29 + 72,38");
l(8,15,"12345 - 67890 - 12345 - 67890 - 12345 - 67890 - 12345");
l(8,16,"11.589,45 + 31.342,09 + 45.602,43 + 89.459,32 + 55.298,24");
l(8,17,"ägg 12,80 bacon 27,50 smör 17,45 ost 43,20 grädde 11,75");
l(8,18,"till - 0805 1205 1605 2005 från - 0935 1335 1735 2135");
l(8,19,"18 mars 19 maj 17 juli 21 september 18 november 19 januari");
l(8,20,"hem 0472-8271 arb 0472-2293 fax 0472-1826 modem 0470-2319");
l(9,1,"aA, aA, aA, aA, aA, fF, fF, fF, fF, jJ, jJ, jJ, jJ, öÖ, öÖ.");
l(9,2,"sS, sS, sS, dD, dD, dD, lL, lL, lL, kK, kK, kK, hH, hH, hH.");
l(9,3,"Ada, Johan, Sara, David, Lars, Fanny, Henry, Gunnel.");
l(9,4,"Adolf, Jenny, Sofia, Dagmar, Lilly, Frans, Harald, Gun.");
l(9,5,"Erik, Ulla, Ronny, Yngve, Torgil, Iris, Olof, Peter.");
l(9,6,"Edvard, Urban, Rikard, Ylva, Ture, Ingrid, Olivia, Pernilla.");
l(9,7,"Nils-Olof, Ann-Christin, Lars-Göran, Britt-Marie, Eva-Lotta.");
l(9,8,"Per-Gustaf, Ulla-Stina, Ann-Marie, Karl-Åke, Sten-Erik.");
l(9,9,"1989, (89), 7/7, 7/7, 0=0, 0=0, +?+?+?, F1!, F1!, 35 % 35 %");
l(9,10,"Paul; Magnus; :Östen: :Christina: :Elisabet: :Jan: ;Rolf;");
l(9,11,"Stockholm, Göteborg, Malmö, Västerås, Uppsala, Jönköping.");
l(9,12,"England, Japan, Brazilien, Skottland, Irland, Frankrike.");
l(9,13,"SAAB, Volvo, VAG, Audi, Ford, Mazda, Toyota, Renault.");
l(9,14,"A - B - C - D - E. abcde ABCDE. (abcde:ABCDE), (a/A,b/B,c/C).");
l(9,15,"Temperaturer: Rom 27(28), Madrid 34(29), Paris 17(24);");
l(9,16,"Resultat: IFK Göteborg-Malmö FF 2-2 (1-1), AIK-Öster 2-1 (0-1).");
l(9,17,"Frågor: När? Hur ofta? Hur många? Varför? Är du säker?");
l(9,18,"Pingis VM-guld, EM-silver, SM-brons, men DM gick åt skogen.");
l(9,19,"Lön: 200 kr/tim. - Skatt (45 %) = 110 kr/tim * 20 tim = 2200:- kr.");
l(9,20,"Aldrig mer! Usch! Vad hemskt! Hur kunde du? Skäms du inte?");
l(10,1,"Den första elektroniska datorn tillverkades redan 1946.\nDen kallades ENIAC och omfattade mer än 18 000 rör, sådana\nsom användes i radio- och TV-apparater förr. Som du kan\nföreställa dig var detta en väldigt stor maskin. Den tog\nensam upp nästan en hel byggnad och vägde 30 ton vilket är\nlika mycket som 30 småbilar. ENIAC användes i ungefär 10 år,\nmen trots sin storlek kunde den inte göra mer än vad en vanlig\nfickräknare klarar idag.");
l(10,2,"Hej BB!\n\nPå semestern hittade jag en hel rad konstiga saker. Här kommer \nen lista över tre av dem...\n\n1. En hög med tomma spaghettiförpackningar - hur många som helst!\n\n2. En kastrull gjord av trä. Den var avlång och kunde säkert \nanvändas till att koka spaghetti i!\n\n3. En tågbiljett mellan Dover och Brighton.\n\nAllt hittade jag i ett gammalt hus med en skylt där det stod - \nSEGare segrar. Vad tror du?\n\nHälsningar Sofia.");
l(10,3,"Ny biodator klar att ta över människans roll\n--------------------------------------------\nI Rom finns nu en prototyp av en mänsklig dator\nsom kallas för MANDY. Datorn har en biologisk\nprocessor och har egna känslor och sinnen.\n\nDet största problemet för närvarande är att ingen\nkan bestämma MANDYs kön, vilket har gett datorn\npsykiska besvär och dåligt självförtroende.\n\nI Rom är man dock inte orolig. Påven har kallats\nin för att döpa underbarnet och myndigheterna\nhoppas samtidigt på ett officiellt uttalande.");
l(10,4,"Forskare hittar nytt användningsområde för penicillin\n\nEn forskare i Göteborg, Doc. Danny Duktig, tros under vinter-\nmånaderna ha hittat en oväntad användning för penicillin.\nDanny hade köpt renoveringstabletter till sin utslitna\nbilmotor men förväxlade dem med sina penicillintabletter.\nResultatet blev att hans normalt svårstartade bil tände så\nfort han vred om nyckeln.\n\nUpprepade försök med pencillintabletter visade ett en tablett\nom dagen vid kallt väder gjorde bilen lättstartad. Danny tror\nockså att bensinförbrukning har minskat med ungefär 25 %.");
l(10,5,"Vad är egentligen en dator?\n\nMed enkla ord är en dator inte mer än en elektrisk anordning\nprecis som din TV eller frys som har utvecklats för att kunna\nutföra speciella uppgifter. Till exempel kan du använda din\ndator som en skrivmaskin för att skriva brev, som en fick-\nräknare för att göra uträkningar, eller som en TV för att visa\nbilder och ritningar.\n\nDu kan också använda den för att lagra telefonnummer, för att\nspela spel, för att göra ritningar eller original för utskrift.\nDatorer kan också användas för att styra produktionslinjer i\nt ex bilfabriker.\n\nPrecis som andra elektriska anordningar kan datorer gå sönder\noch orsaka problem. Var dock skeptisk när du hör att 'det var\ndatorn som gjorde fel...'. Det är nästan alltid så att det är\nett mänskligt fel, som orsakar det där brevet, vilket uppmanar\ndig att omedelbart betala in skulden på 2 245 376 kronor.");
l(10,6,"Stor matematikundersökning klar igår\n\nSent igår blev omröstningen klar i den mycket omdebatterade\nundersökningen av matematiska kunskaper hos grundskolelever.\n\nSkolöverstyrelsen lämnade följande resultat:\nAv de 93 representanterna var\n      53 allmänt nöjda,\n      37 allmänt missnöjda och\n       5 la ner sina röster.\n\nOrdförande Henry Kanallt sa efteråt: - Det här resultatet är ett\nklart bevis på att vi här i Sverige verkligen kan vår matematik.");
l(10,7,"Hej mormor!\n\nJag ville bara tala om för dig att jag har lärt mig att koka \nte. Så här gör man...\n\n1. Mät upp vattnet i en kopp och häll vattnet i en kastrull. \nSätt kastrullen på spisen och vänta ett tag.\n\n2. När vattnet kokar kan du lägga i en tepåse i koppen och hälla \ni vattnet. Du måste göra det försiktigt så att du inte bränner \ndig.\n\n3. Vänta 5 minuter och ta ur tepåsen. Om du vill ha mjölk eller \nsocker kan du lägga i det nu. Drick teet innan det blir kallt. \nPappa säger att te är mycket godare än kaffe.\n\nHej på dig från Alexander.\n\nJag glömde att säga att du måste sätta på spisen först och stänga \nav den sedan. Det vet en mormor redan om.");
l(10,8,"VM 1958 - Grundspel grupp III\n-----------------------------\nSverige - Mexico  3-0\nUngern  - Wales   1-1\nMexico  - Wales   1-1\nSverige - Ungern  2-1\nSverige - Wales   0-0\nUngern  - Mexico  4-0\n\nSverige 3  2  1  0  5 - 1  5\nWales   3  0  3  0  2 - 2  3\n----------------------------\nUngern  3  1  1  1  6 - 3  3\nMexico  3  0  1  2  1 - 8  1");
l(10,9,"What happens when you press a key?\n\nWhen you press a key, a code number for the key pressed\nis automatically generated. That code number is placed\nin the keyboard buffer which is a kind of waiting room\nfor keyboard code numbers.\n\nYour computer checks at regular intervals -- many times\na second -- to see if any code number is waiting to be\npicked up from the keyboard buffer. If so, the code number\nis instantly moved to the computer's processor and assessed.\nThe key stroke is then usually sent to the monitor so that\nyou see what key you have pressed.\n\nPlease understand that all this happens in a flash. In fact\nyour computer spends most of its time waiting for you to press\na key!");
l(10,10,"Översättning till engelska av boken.\n\nPris:\n63.000:-.\n\nFörslag till tidsplan:\nv. 18-27    Översättning\nv. 28-31    Korrektur, kvalitetskontroll & kodning\nv. 31       Leverans av kodat manus\nv. ??       Korrekturläsning av 1:a spaltkorrektur\n\nTidsplanen förutsätter omgående besked (senast v 18) samt\nsnabbleverans av 2 kopior på boken. \n\nProjektledare: Peter Hansson\nÖversättning:  Tim Hughes\n\nMed vänliga hälsningar\n\nPeter Hansson\nEBG");
